name: Daily Backtest MY Dataset

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download and install TA-Lib
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        sudo ldconfig
        cd ..

    - name: Verify TA-Lib installation
      run: |
        ls -l /usr/lib/libta_lib*
        ls -l /usr/include/ta-lib/ta_libc.h

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        export TA_INCLUDE_PATH="/usr/include"
        export TA_LIBRARY_PATH="/usr/lib"
        echo "Attempting to install TA-Lib==0.4.24 with TA_LIBRARY_PATH=${TA_LIBRARY_PATH} and TA_INCLUDE_PATH=${TA_INCLUDE_PATH}"
        pip install --no-cache-dir --verbose "TA-Lib==0.4.24"
        pip install -r requirements.txt

    - name: Run backtest script
      run: python Backtesting/main.py --dataset MY