    name: Daily Backtest MY Dataset

    on:
      schedule:
        # 每天 UTC 时间 00:30 运行 (对应 UTC+7 07:30)
        - cron: '30 0 * * *'
      workflow_dispatch:

    jobs:
      run-backtest:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install TA-Lib dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y ta-lib

        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run backtest script
          run: python Backtesting/main.py --dataset MY