name: Daily Backtest MY Dataset

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install TA-Lib C library and build dependencies
      run: |
        sudo apt-get update
        # Installs ta-lib library and headers, plus build tools
        sudo apt-get install -y build-essential libta-lib-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Attempting to install TA-Lib Python wrapper..."
        pip install TA-Lib==0.4.24
        pip install -r requirements.txt

    - name: Run backtest script
      run: python Backtesting/main.py --dataset MY