name: Daily Backtest MY Dataset

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies (build-essential, wget)
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download, compile, and install TA-Lib C library (v0.4.0)
      run: |
        # ... (Keep the C library compilation steps exactly as before) ...
        echo "Downloading TA-Lib C library source..."
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        echo "Extracting source..."
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        echo "Configuring TA-Lib C library (prefix=/usr)..."
        ./configure --prefix=/usr
        echo "Compiling TA-Lib C library..."
        make
        echo "Installing TA-Lib C library..."
        sudo make install
        echo "Updating dynamic linker cache..."
        sudo ldconfig
        cd ..
        echo "TA-Lib C library installation complete."

    - name: Verify TA-Lib C library installation
      run: |
        # ... (Keep the verification steps exactly as before) ...
        echo "Verifying TA-Lib library files in /usr/lib..."
        ls -l /usr/lib/libta_lib* || (echo "Library file not found in /usr/lib!" && exit 1)
        echo "Verifying TA-Lib header file in /usr/include/ta-lib..."
        ls -l /usr/include/ta-lib/ta_libc.h || (echo "Header file not found in /usr/include/ta-lib!" && exit 1)

    - name: Install Python Build Dependencies for TA-Lib First
      run: |
        python -m pip install --upgrade pip
        # Install Cython and NumPy<2 BEFORE attempting to install TA-Lib
        # This satisfies the [build-system] requirements in TA-Lib's pyproject.toml
        echo "Installing Cython and NumPy<2..."
        pip install "cython>=0.29.36" "numpy<2" --verbose

    - name: Install TA-Lib Python Wrapper Separately
      run: |
        # Set environment variables again just in case (might not be strictly needed if set globally)
        export TA_INCLUDE_PATH="/usr/include"
        export TA_LIBRARY_PATH="/usr/lib"
        export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
        echo "TA_INCLUDE_PATH=${TA_INCLUDE_PATH}"
        echo "TA_LIBRARY_PATH=${TA_LIBRARY_PATH}"
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

        # Now install TA-Lib using --no-build-isolation
        # Since build deps (Cython, NumPy) are already installed, this should work
        echo "Installing TA-Lib==0.4.29 (or your chosen 0.4.x version)..."
        pip install --no-build-isolation TA-Lib==0.4.29 --verbose # Make sure this matches requirements.txt

    - name: Install Remaining Python Dependencies
      run: |
        echo "Installing remaining requirements from requirements.txt..."
        # Pip will skip numpy and TA-Lib as they are already installed
        pip install -r requirements.txt --verbose

    - name: Run backtest script
      run: python Backtesting/main.py --dataset MY