name: Daily Backtest MY Dataset

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-backtest:
    # 可以继续使用 ubuntu-22.04 或换回 ubuntu-latest，因为我们不再依赖 apt 安装 ta-lib C 库
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies (build-essential, wget)
      # 只需要基本的编译工具和下载工具
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download, compile, and install TA-Lib C library
      run: |
        echo "Downloading TA-Lib C library source..."
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        echo "Extracting source..."
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        echo "Configuring TA-Lib C library (prefix=/usr)..."
        ./configure --prefix=/usr
        echo "Compiling TA-Lib C library..."
        make
        echo "Installing TA-Lib C library..."
        sudo make install
        # 确保动态链接器能找到新安装的库
        echo "Updating dynamic linker cache..."
        sudo ldconfig
        cd ..
        echo "TA-Lib C library installation complete."

    - name: Verify TA-Lib C library installation (Optional but helpful)
      run: |
        echo "Verifying TA-Lib library files in /usr/lib..."
        ls -l /usr/lib/libta_lib* || echo "Library file not found in /usr/lib"
        echo "Verifying TA-Lib header file in /usr/include/ta-lib..."
        ls -l /usr/include/ta-lib/ta_libc.h || echo "Header file not found in /usr/include/ta-lib"

    - name: Install Python dependencies (controlled order)
      run: |
        python -m pip install --upgrade pip

        # 1. 设置环境变量指向手动安装的 C 库路径
        export TA_INCLUDE_PATH="/usr/include"
        export TA_LIBRARY_PATH="/usr/lib"
        echo "TA_INCLUDE_PATH=${TA_INCLUDE_PATH}"
        echo "TA_LIBRARY_PATH=${TA_LIBRARY_PATH}"

        # 2. 安装 requirements.txt 中的其余包
        echo "Installing remaining requirements..."
        pip install --no-build-isolation -r requirements.txt

    - name: Run backtest script
      run: python Backtesting/main.py --dataset MY